"use client";
import { store } from "@/providers";
import { Provider } from "react-redux";

/*export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{<Provider store={store}>children</Provider>}</body>
    </html>
  );
}
