name: Server CI

on:
  push:
    paths:
      - apps/server/**
      
env:
  PORT: 3333
  ALLOWED_ORIGIN_CLIENT: "http://localhost:3333"
  ALLOWED_ORIGIN_Server: "http://localhost:4200"
  DB_HOST: 'localhost'
  DB_PORT: 5432
  DB_PASSWORD: 'postgres'
  DB_DATABASE: 'postgres'
  DB_USER: 'postgres'

jobs:
  Run-Client-Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci --force
      - run: npm run back-end-test

  Run-Lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i --force
      - run: npm run build --if-present
      - run: npm run back-end-lint
