# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'
on:
  push:
    branches:
    - main
    paths:
    - packages/client/**

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_TASKMANAGER_ATOMS_TOKEN }}
          workingDir: packages/client
